
pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'

        IMAGE_NAME = 'pharma-ui'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Fetch AWS Info') {
            steps {
                script {
                // Get NLB DNS
                env.NLB_DNS = sh(
                    script: "kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'",
                    returnStdout: true
                ).trim()

                // Get AWS Account ID
                env.AWS_ACCOUNT = sh(
                    script: "aws sts get-caller-identity --query Account --output text",
                    returnStdout: true
                ).trim()

                env.ECR_REPO = "${env.AWS_ACCOUNT}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.IMAGE_NAME}"
                }
            }
        }

        stage('Checkout') {
            steps {
                git(
                    branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Chaveen123/pharma-platform.git'
                )
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} \
                services/pharma-ui
                '''
            }
        }

        stage('Login ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin \
                ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
                ${ECR_REPO}:${IMAGE_TAG}

                docker push ${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Update Helm & Manifests') {
            steps {
                script {
                sh """
                    sed -i 's|repository:.*|repository: ${ECR_REPO}|' ops/envs/values-pharma-ui.yaml
                    sed -i 's|tag:.*|tag: ${IMAGE_TAG}|' ops/envs/values-pharma-ui.yaml
                    sed -i 's|image:.*|image: ${ECR_REPO}:${IMAGE_TAG}|' ops/k8s-manifests/pharma-ui/deployment.yaml
                    sed -i 's|host:.*|host: ${NLB_DNS}|' ops/k8s-manifests/pharma-ui/ingress.yaml
                """
                }
            }
        }

        stage('Commit & Push Changes') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    sh """
                    git config --global user.email "jenkins@ci.local"
                    git config --global user.name "Jenkins CI"

                    git add ops/envs/values-pharma-ui.yaml ops/k8s-manifests/pharma-ui/deployment.yaml ops/k8s-manifests/pharma-ui/ingress.yaml
                    git commit -m "Update image tag ${IMAGE_TAG}"
                    git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Chaveen123/pharma-platform.git HEAD:main
                    """
                }
            }       
        } 
    }
}
