
pipeline {
    agent any

    triggers {
        // Option 1: Polling (not ideal for large repos)
        pollSCM('H/2 * * * *') // every 5 minutes
        // Option 2: Webhook (preferred) → configure GitHub/GitLab webhook to Jenkins
    }

    environment {
        AWS_REGION = 'us-east-1'
        
        SRC_PATH = 'services/auth-service'
        IMAGE_NAME = 'auth-service'
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Chaveen123/pharma-platform.git'
                )
            }
        }
        
        stage('Fetch AWS Info') {
            steps {
                script {
                env.COMMIT_HASH = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                
                env.IMAGE_TAG   = "${IMAGE_NAME}:${COMMIT_HASH}"

                // Get AWS Account ID
                env.AWS_ACCOUNT = sh(
                    script: "aws sts get-caller-identity --query Account --output text",
                    returnStdout: true
                ).trim()

                // Get RDS Endpoint
                env.RDS_ENDPOINT = sh(
                    script: "aws rds describe-db-instances --db-instance-identifier pharmacy-app-dev-postgres --query 'DBInstances[0].Endpoint.Address' --output text",
                    returnStdout: true
                 ).trim()

                env.ECR_REPO = "${env.AWS_ACCOUNT}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.IMAGE_NAME}"
                }
            }
        }

        stage('Detect Changes') {
            steps {
                script {
                    def changes = sh(
                        script: "git diff --name-only HEAD~1 HEAD | grep '^${SRC_PATH}/' || true",
                        returnStdout: true
                    ).trim()
                    if (changes == "") {
                        currentBuild.result = 'SUCCESS'
                        error("No changes in ${IMAGE_NAME}, skipping build")
                    }
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    sh """
                        docker build -t ${ECR_REPO}:${COMMIT_HASH} ${SRC_PATH}
                    """
                }
            }
        }

        stage('Login ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin \
                ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Push Image') {
            steps {
                script {
                    sh """
                        docker push ${ECR_REPO}:${COMMIT_HASH}
                    """
                }
            }
        }

        stage('Update Helm & Manifests') {
            steps {
                script {
                    sh """
                        sed -i 's|repository:.*|repository: ${ECR_REPO}|' ops/envs/values-auth-service.yaml
                        sed -i 's|tag:.*|tag: ${COMMIT_HASH}|' ops/envs/values-auth-service.yaml
                        sed -i 's|DB_HOST:.*|DB_HOST: ${RDS_ENDPOINT}|' ops/envs/values-auth-service.yaml
                    """
                }
            }
        }

        stage('Commit & Push Changes') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    sh """
                    git config --global user.email "jenkins@ci.local"
                    git config --global user.name "Jenkins CI"

                    git add ops/envs/values-auth-service.yaml
                    git commit -m "Update image tag ${IMAGE_TAG}"
                    git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Chaveen123/pharma-platform.git HEAD:main
                    """
                }
            }       
        } 
    }
}
